'use client';

import { useRef } from 'react';
import {
  Building2,
  Calendar,
  FileText,
  ArrowLeft,
  Download,
  Truck,
} from 'lucide-react';
import { useRouter } from 'next/navigation';
import StockTable from '../components/StockTable';

interface Props {
  reportType: string;
}

export default function InventoryReportA4({ reportType }: Props) {
  const router = useRouter();
  const reportRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    if (!reportRef.current) return;

    const printWindow = window.open('', '_blank', 'width=1200,height=900');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>Inventory Report</title>
          <style>
            body { margin:0; padding:0; font-family:sans-serif; color:#000; }
            table { width:100%; border-collapse:collapse; }
            th, td { border:1px solid #333; padding:8px; font-size:12px; }
            th { background:#f3f3f3; font-weight:bold; }
            h1,h2,p { margin:0; }
            .text-right { text-align:right; }
          </style>
        </head>
        <body>
          ${reportRef.current.innerHTML}
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 300);
  };

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-[220mm] mx-auto mb-8 flex items-center justify-between">
        <button
          onClick={() => router.back()}
          className="flex items-center gap-2 px-5 py-2.5 bg-white border border-gray-300 
                   rounded-lg shadow-sm hover:bg-gray-50 hover:border-gray-400 
                   transition-all duration-200 font-medium text-gray-700"
        >
          <ArrowLeft size={18} />
          Back
        </button>

        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-6 py-2.5 bg-blue-600 text-white 
                   rounded-lg shadow-md hover:bg-blue-700 active:bg-blue-800 
                   transition-all duration-200 font-medium"
        >
          <Download size={18} />
          Download PDF
        </button>
      </div>

      <div
        ref={reportRef}
        className="bg-white text-black mx-auto shadow-2xl"
        style={{
          width: '210mm',
          minHeight: '297mm',
          padding: '20mm 22mm',
          boxSizing: 'border-box',
        }}
      >
        {/* Header */}
        <header className="flex justify-between items-start border-b-2 border-gray-800 pb-6 mb-8">
          <div>
            <div className="flex items-center gap-3">
              <Building2 size={32} strokeWidth={2.2} className="text-gray-800" />
              <h1 className="text-2xl font-bold text-gray-900">
                Coal Washery Management System
              </h1>
            </div>
            <p className="mt-1 text-sm text-gray-600 font-medium">
              Operational Inventory Report
            </p>
          </div>

          <div className="text-right text-sm space-y-2">
            <p className="flex items-center justify-end gap-2 text-gray-700">
              <FileText size={16} />
              <span className="font-medium">{reportType}</span>
            </p>
            <p className="flex items-center justify-end gap-2 text-gray-700">
              <Calendar size={16} />
              {new Date().toLocaleDateString('en-IN', {
                day: 'numeric',
                month: 'long',
                year: 'numeric',
              })}
            </p>
          </div>
        </header>

        {/* Meta Information */}
        <div className="grid grid-cols-2 gap-12 mb-10 text-sm">
          <div className="space-y-2">
            <p>
              <strong className="text-gray-800">Plant Name:</strong> XYZ Coal Washery
            </p>
            <p>
              <strong className="text-gray-800">Location:</strong>  India
            </p>
          </div>

          <div className="text-right space-y-2">
            <p>
              <strong className="text-gray-800">Generated By:</strong> System
            </p>
            <p>
              <strong className="text-gray-800">Status:</strong>{' '}
              <span className="text-green-700 font-semibold">Verified</span>
            </p>
          </div>
        </div>

        {/* Stock Table */}
        <StockTable />

      </div>
    </div>
  );
}
