// app/dashboard/weighbridge/reports/page.tsx
'use client';

import { useRef } from 'react';
import {
  Scale,
  Calendar,
  FileText,
  ArrowLeft,
  Download,
} from 'lucide-react';
import { useRouter } from 'next/navigation';

// Mock data (replace with real data in production)
const weighbridgeDailySummary = [
  { date: "12 Jan 2026", vehicleIn: 42, vehicleOut: 39, inwardWt: 1240, outwardWt: 1185 },
  { date: "11 Jan 2026", vehicleIn: 31, vehicleOut: 29, inwardWt: 980, outwardWt: 945 },
  { date: "10 Jan 2026", vehicleIn: 38, vehicleOut: 36, inwardWt: 1120, outwardWt: 1090 },
  { date: "09 Jan 2026", vehicleIn: 35, vehicleOut: 33, inwardWt: 1085, outwardWt: 1020 },
];

export default function WeighbridgeDailyReport() {
  const router = useRouter();
  const reportRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    if (!reportRef.current) return;

    const printWindow = window.open('', '_blank', 'width=1200,height=900');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>Weighbridge Daily Summary</title>
          <style>
            body { margin:0; padding:0; font-family:sans-serif; color:#000; }
            table { width:100%; border-collapse:collapse; }
            th, td { border:1px solid #333; padding:8px; font-size:12px; }
            th { background:#f3f3f3; font-weight:bold; }
            h1,h2,p { margin:0; }
            .text-right { text-align:right; }
          </style>
        </head>
        <body>
          ${reportRef.current.innerHTML}
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 300);
  };

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4 sm:px-6 lg:px-8">
      {/* Control Buttons */}
      <div className="max-w-[220mm] mx-auto mb-8 flex items-center justify-between">
        <button
          onClick={() => router.back()}
          className="flex items-center gap-2 px-5 py-2.5 bg-white border border-gray-300 
                   rounded-lg shadow-sm hover:bg-gray-50 hover:border-gray-400 
                   transition-all duration-200 font-medium text-gray-700"
        >
          <ArrowLeft size={18} />
          Back
        </button>

        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-6 py-2.5 bg-blue-600 text-white 
                   rounded-lg shadow-md hover:bg-blue-700 active:bg-blue-800 
                   transition-all duration-200 font-medium"
        >
          <Download size={18} />
          Download PDF
        </button>
      </div>

      {/* A4 Report Content */}
      <div
        ref={reportRef}
        className="bg-white text-black mx-auto shadow-2xl"
        style={{
          width: '210mm',
          minHeight: '297mm',
          padding: '20mm 22mm',
          boxSizing: 'border-box',
        }}
      >
        {/* Header */}
        <header className="flex justify-between items-start border-b-2 border-gray-800 pb-6 mb-8">
          <div>
            <div className="flex items-center gap-3">
              <Scale size={32} strokeWidth={2.2} className="text-gray-800" />
              <h1 className="text-2xl font-bold text-gray-900">
                Coal Washery Weighbridge
              </h1>
            </div>
            <p className="mt-1 text-sm text-gray-600 font-medium">
              Daily Summary Report
            </p>
          </div>

          <div className="text-right text-sm space-y-2">
            <p className="flex items-center justify-end gap-2 text-gray-700">
              <FileText size={16} />
              <span className="font-medium">Daily Transaction</span>
            </p>
            <p className="flex items-center justify-end gap-2 text-gray-700">
              <Calendar size={16} />
              {new Date().toLocaleDateString('en-IN', {
                day: 'numeric',
                month: 'long',
                year: 'numeric',
              })}
            </p>
          </div>
        </header>

        {/* Meta Information */}
        <div className="grid grid-cols-2 gap-12 mb-10 text-sm">
          <div className="space-y-2">
            <p>
              <strong className="text-gray-800">Plant Name:</strong> XYZ Coal Washery
            </p>
            <p>
              <strong className="text-gray-800">Location:</strong> Raipur, Chhattisgarh
            </p>
          </div>

          <div className="text-right space-y-2">
            <p>
              <strong className="text-gray-800">Generated By:</strong> System
            </p>
            <p>
              <strong className="text-gray-800">Status:</strong>{' '}
              <span className="text-green-700 font-semibold">Verified</span>
            </p>
          </div>
        </div>

        {/* Main Table */}
        <table className="w-full border-collapse text-sm">
  <thead>
    <tr className="bg-gray-100 text-gray-800">
      <th className="border border-gray-300 px-4 py-3 text-left font-semibold">Date</th>
      <th className="border border-gray-300 px-4 py-3 text-center font-semibold">Vehicles In</th>
      <th className="border border-gray-300 px-4 py-3 text-center font-semibold">Vehicles Out</th>
      <th className="border border-gray-300 px-4 py-3 text-right font-semibold">Inward (MT)</th>
      <th className="border border-gray-300 px-4 py-3 text-right font-semibold">Outward (MT)</th>
      <th className="border border-gray-300 px-4 py-3 text-right font-semibold">Net (MT)</th>
    </tr>
  </thead>
  <tbody>
    {weighbridgeDailySummary.map((row, i) => {
      const net = row.inwardWt - row.outwardWt;
      
      return (
        <tr 
          key={i}
          className="hover:bg-gray-50/70 transition-colors"
        >
          <td className="border border-gray-200 px-4 py-3 font-medium">{row.date}</td>
          <td className="border border-gray-200 px-4 py-3 text-center">{row.vehicleIn.toLocaleString()}</td>
          <td className="border border-gray-200 px-4 py-3 text-center">{row.vehicleOut.toLocaleString()}</td>
          <td className="border border-gray-200 px-4 py-3 text-right">{row.inwardWt.toLocaleString()}</td>
          <td className="border border-gray-200 px-4 py-3 text-right">{row.outwardWt.toLocaleString()}</td>
          <td 
            className={`
              border border-gray-200 px-4 py-3 text-right font-semibold
              ${net > 0 ? 'text-emerald-700' : 
                net < 0 ? 'text-red-700' : 'text-gray-900'}
            `}
          >
            {net > 0 ? '+' : ''}{net.toLocaleString()}
          </td>
        </tr>
      );
    })}
  </tbody>
</table>

        {/* Footer */}
        <div className="mt-12 pt-6 text-center text-xs text-gray-600 border-t border-gray-300">
          Confidential • For Internal Use Only • Generated by Coal Washery Management System
        </div>
      </div>
    </div>
  );
}